### ISSUE TITLE
[Bug] Crash when requesting changes via chat on a ticket in review

### ISSUE THREAD

**Issue by alcibiadesc** [BloopAI/vibe-kanban#723]
**Description**  
When a ticket is in **Review** status and a user writes in the chat to request a change, the application crashes. The error indicates that more than one execution process is running simultaneously.  

**Steps to Reproduce**  
1. Move a ticket to **Review**.  
2. Open the chat attached to the ticket.  
3. Write a message requesting a change.  
4. Observe the crash.  

**Expected Behavior**  
The chat should allow sending messages and requesting changes without breaking the app.  

**Actual Behavior**  
The app crashes with a `More than one running execution process found` error.  

**Possible Cause**  
It seems multiple conversation execution processes are started when sending a message during review. The app does not properly handle concurrent executions and triggers the ErrorBoundary.  

**Log Error**
UI: An error has occurred
CONSOLE: 

```
hook.js:608 Error: More than one running execution process found
    at f (useConversationHistory.ts:164:13)
    at useConversationHistory.ts:444:28
Caused by: React ErrorBoundary Error: More than one running execution process found
    at E5e (VirtualizedList.tsx:44:28)
    at Rj (LogsTab.tsx:8:20)
    at div
    at main
    at div
    at div
    at div
    at qNe (ReviewProvider.tsx:40:34)
    at KBe (ProcessSelectionContext.tsx:25:3)
    at pUe (TaskDetailsPanel.tsx:49:3)
    at div
    at div
    at pT (project-tasks.tsx:29:44)
    at div
    at div
    at aTe (search-context.tsx:23:34)
    at aRt (style-override.tsx:24:3)
    at iTe (theme-provider.tsx:22:3)
    at mRt (App.tsx:40:52)
    at JTe (project-context.tsx:21:35)
    at WNe (config-provider.tsx:61:38)
    at gRt

```

**Comment by LSRCT** [comment]
Fixed by #726, should be on npm in an hour or so.
Thanks for reporting!

**Comment by alcibiadesc** [comment]
## Bug Description
Hi @LSRCT ,  

Sorry, but the issue is still not resolved. The following flow reproduces the problem:

1. Create a ticket.
2. Wait until it moves to the "In Review" column.
3. Open the ticket in full screen.
4. Click the "DEV" button to start the dev server.
5. Write a message.
6. Click "Send".

After performing these steps, the error message appears:

**"An error has occurred."**

**Comment by alcibiadesc** [comment]
## Bug Description

Hi @LSRCT,

Sorry, but the issue is still not resolved. The following flow reproduces the problem:

1. Create a ticket.
2. Wait until it moves to the "In Review" column.
3. Open the ticket in full screen.
4. Click the "DEV" button to start the dev server.
5. Write a message.
6. Click "Send".

After performing these steps, the error message appears:

**"An error has occurred."**

<img width="2022" height="1646" alt="Image" src="https://github.com/user-attachments/assets/d843c27f-cb4b-49e2-bb4b-f95bbcad0936" />


<img width="1958" height="806" alt="Image" src="https://github.com/user-attachments/assets/a94adcbe-1969-4f21-a3dc-4a580e8a54ab" />

**Comment by alcibiadesc** [comment]
Fixed in #736
